### PR TITLE
Add ja translation about dragoon.

### PR DESCRIPTION
**Pull request by DaisukeSawada**

### CODE REVIEW

**Comment by NamelessFaceless** [comment]
This is something you should do on our crowdin service rather than a PR. I'm not too sure where it's listed.

**Comment by ackwell** [comment]
It's in the site header - not sure if crowdin can sync or not.

**Comment by NamelessFaceless** [comment]
I have no fuckin' clue, mate.

**Comment by DaisukeSawada** [comment]
I'm sorry. I did not understand anything.I will look at crowdin.

**Comment by ackwell** [comment]
Don't worry about it mate, it should transfer across quite easily. Let me
know here or on discord if you need a hand!

**Pull request closed without merging**
