### PR TITLE
[GNB] 6.1 Support

### PR DESCRIPTION
**Pull request by Rjb99**
10 -> 3 for all tank stances. Much Change.

### CODE REVIEW

**Comment by ayyaruq** [comment]
Needs rebasing or whatever homie. Layers are merged, so just need the changes to the layer.

**Comment by Rjb99** [comment]
fixed. Should be good to merge now

**Review by suShirow — APPROVED** [review]

**Comment by ayyaruq** [comment]
As per ack's instructions in Discord, there's no need for a changelog if nothing changed, we don't need entries just for patch flagging.

**Review by suShirow — CHANGES_REQUESTED** [review]
So sorry, as acc and ack said we gotta remove changelogs

**Comment by Rjb99** [comment]
I added Royal Guard's CD change to the changelog since I did make that minor change. do we still want it dropped/moved elsewhere since it's a change to all 4 tanks? Change really only impacts timeline and minorly at that.

**Comment by ayyaruq** [comment]
Another PR already made that change, and for all tanks, was merged a few days ago. This PR doesn't set that. Also, that change was only in data, not analyser code, so you still don't need a changelog for it since users can't see anything in data.

**Review by suShirow — APPROVED** [review]

**Pull request merged**
