### PR TITLE
[MCH] 6.1 bump

### PR DESCRIPTION
**Pull request by hintxiv**
I don't think we're using this potency data for anything, but I updated it. Merge after #1661

### CODE REVIEW

**Review by ayyaruq — CHANGES_REQUESTED** [review]
Please use patch layers for this.

**Review by suShirow — CHANGES_REQUESTED** [review]
Since this is a major patch, I think we should change these in the data layers to be created in https://github.com/xivanalysis/xivanalysis/pull/1663, or there will be funky differences between our potencies and those that CN and KR get.

**Comment by hintxiv** [comment]
@ayyaruq @suShirow these potency numbers aren't used anywhere and weren't up to date in the first place, there's no point in layering the change. I just updated them for correctness while scrolling through data.

**Comment by suShirow** [comment]
> @ayyaruq @suShirow these potency numbers aren't used anywhere and weren't up to date in the first place, there's no point in layering the change. I just updated them for correctness while scrolling through data.

Oh, okay well alright then.

**Review by suShirow — APPROVED** [review]

**Comment by ayyaruq** [comment]
If the potencies aren't used then they should probably be removed, but if they're gonna be there then the values in the root files should reflect 6.0 values and patches should override as needed. Generally we only keep potency where it's needed tho.

**Comment by ayyaruq** [comment]
Might need to re-merge `endwalker` into this.

**Review by ayyaruq — APPROVED** [review]
Thanks for re-syncing with `endwalker`, LGTM.

**Pull request merged**
