### PR TITLE
Add mitigation timeline

### PR DESCRIPTION
**Pull request by wxiaoying**
Shows mitigations used in timeline (default collapsed). Also adds some mitigations that were missing.

### CODE REVIEW

**Review by ackwell — CHANGES_REQUESTED** [review]
Heyo! Thanks for the contribution.

It looks like this is using the old `Module` system - while a vast majority of the codebase is still using this system, we're currently undergoing work to port analysis onto the new `Analyser` system.

As a result, _especially_ for `parser/core`, I'm not going to be accepting _new_ modules written on the old system. (Doubly so if it's touching `AdditionalEvents`!)

The only dependency here that you might be missing on said new system is the `isActive` check, but bar that most stuff should port across.

Please feel free to drop past the discord server to chat if you've got any questions on how to get started &c!

**Comment by wxiaoying** [comment]
Okay, that sounds good to me, this is heavily copied from the raid buffs module, so I suppose I'll wait for that to be ported and revisit.

**Comment by ayyaruq** [comment]
RaidBuffs has been migrated to Analyser now, so may want to look at this again now.

**Comment by ackwell** [comment]
Heyo! This has sit dormant for a while sorry - we're doing some cleanup for the EW branch cut.
If you'd like to continue with this, feel free to open a new PR targeting the endwalker branch (with the new analyser system!)

**Pull request closed without merging**
