### PR TITLE
Finalise analyser migration

### PR DESCRIPTION
**Pull request by ackwell**
We got there. It's done.

This is a project that, effectively, started over 3 years ago.
This is a project that has been an ongoing concerted effort from multiple developers for most of a year.

We got there.

---

This PR removes the _bulk_ of the legacy module system. There's some bits and pieces that still need to be moved, removed, edited, amended, or otherwise fiddled with - but this gets us 99% of the way there.

Jobs with notable module deletions: BRD, SAM, SMN

DRG's BOTD module has been updated with (hopefully) correct time logic. dunno. someone check please.

The remainder of this work will be long-form and spread over the coming weeks.

I'm still kinda in shock this is happening so hey.

### CODE REVIEW

**Comment by Rjb99** [comment]
The deletion of most of Sam looks good to me. 

Oh wait I'll have to fix it. Oh well, problem for after xpac week

**Comment by KelosPelmand** [comment]
Same, but for SMN.

**Review by ebshimizu — COMMENTED** [review]
DRG's BotD looks good actually. Downtime intersection working properly, timestamps formatted correctly. We're deleting gauge tracking in EW but that also looks like it's working.

**Comment by AkairyuGestalter** [comment]
BLM/DNC tinkerings are good, sadge I missed those timestamp conversions and Improv in DNC Gauge is dying anyways

**Comment by ayyaruq** [comment]
MNK looks fine, WAR mostly fine except I guess I should have imported combos properly lol.

**Pull request merged**
