### PR TITLE
DRG: 6.4 support

### PR DESCRIPTION
**Pull request by ebshimizu**
DRG is the same*

*but with added positional buffs. Since Dragon Sight is still primarily used for damage, it'll typically be used on CD and not for optimizing positionals (and if you're doing that we're going to assume you know what you're doing). This is a lot of words to say there are no plans for additional analysis of DS.

### CODE REVIEW

**Review by nonowazu — APPROVED** [review]
~~Untenable amount of chan~~ Simple one-line change, doesn't impact anything.

**Comment by AkairyuGestalter** [comment]
Question: have we verified that the missed positional checks won't bitch about a nominally missed positional while Dragon Sight is active? We probably ought do that before we say no changes needed

**Comment by ebshimizu** [comment]
> Question: have we verified that the missed positional checks won't bitch about a nominally missed positional while Dragon Sight is active? We probably ought do that before we say no changes needed

good question, my understanding from reading the code and vaguely recalling the discussion from when it was implemented is that the `Positionals` module in core looks at the potency of the relevant actions to determine if a positional would hit, so assuming new DS handles that as it does for other skills (e.g. MNK's riddle of earth) we should be ok.

**Comment by ebshimizu** [comment]
quick striking dummy test shows positionals registering ok: https://xivanalysis.com/fflogs/1xr4C8mwdAVLg3bc/1/1
stood in the front, hit some buttons. DS was active for one FC and one WT.

**Comment by AkairyuGestalter** [comment]
Good enough for me, thanks for checking!

**Review by AkairyuGestalter — APPROVED** [review]

**Pull request merged**
