### PR TITLE
Update AST.ts with correct Collective Unconscious cooldown

### PR DESCRIPTION
**Pull request by danielylee01**
Changed Collective Unconscious's cooldown from 90s to 60s (as it currently is in-game)

### CODE REVIEW

**Review by ayyaruq — CHANGES_REQUESTED** [review]
As this differs per patch, please use layers, you can find the layer override for 5.1 at https://github.com/xivanalysis/xivanalysis/blob/master/src/data/ACTIONS/layers/patch5.1.ts

Since there's already a block for Collective Unconsciousness, you just need to add a line for the cooldown.

**Comment by danielylee01** [comment]
Thanks for the response! Hopefully I did this correctly - let me know if not

**Review by ayyaruq — APPROVED** [review]
Thanks for the fix, I made a small edit for the CI fault on linting. Lines should start with tab indentation instead of spaces or the linter will fail it.

**Comment by danielylee01** [comment]
Awesome! Thanks so much for your hard work on the tool (I use it a lot!) and I'm glad to have been able to help in some way :D

**Pull request merged**
