### PR TITLE
[AST] 7.0 ABC fix (Macrocosmos gcdRecast) and Burst Window Update

### PR DESCRIPTION
**Pull request by otocephaly**
## Pull request type

- [x] This is a bugfix to existing functionality
  - for macrocosmos
- [x] This is a patch bump

## Pull request details

- [x] The goal of this PR is detailed below:
    - Fix ABC caused by missing Macrocosmos gcdRecast (oop)
    - Update Tincture and Divination to work with new burst window (see image below)
       - Note: Cards within the window are included because I didn't want to punish someone for casting a card a GCD early but praise someone who casted a card a GCD late. Please let me know if you disagree with that judgement

- [ ] The job(s) in this patch bump had no changes for this patch
- [ ] The job(s) in this patch bump had only potency changes for this patch, which do not effect analysis
  - [ ] I have updated the data files for all potency changes for this patch
  - [ ] The skills and jobs affected by these potency changes do not track potency for xivanaylsis purposes
- [ ] This is the last PR after all analysis changes for this job have been merged, and now the job is ready to be marked supported for this patch

## Testing / Validation

- [x] I used the log(s) listed below to develop and test this bugfix:
    - https://www.fflogs.com/reports/nPjhzyGpfdLTq7tA#fight=17&source=56

## Job Maintenance
- [x] I have collaborated with one or more job maintainers for the job(s) in this PR while developing it

## Rotation Guide From The Balance
image

### CODE REVIEW

**Comment by otocephaly** [comment]
Here are what the sections look like now

Tincture:
image

Divination:
image

**Comment by otocephaly** [comment]
Updated divination after Rah's comment
image

**Comment by otocephaly** [comment]
Hi @suShirow , here's an example log where a card was played before divination
https://www.fflogs.com/reports/a:7wDKTkJhzaqtMZWr#fight=3&source=245

Here's what it looks like in the PR
image

**Review by mm-rayyan — APPROVED** [review]
The logic checks out even though I can't test it myself right now. If there's a problem after testing we'll just fix it. Thanks for taking care of it! 🦙

**Review by suShirow — APPROVED** [review]
The logic checks out even though I can't test it myself right now. If there's a problem after testing we'll just fix it. Thanks for taking care of it! 🦙

**Pull request merged**
