### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by ackwell**
Enjoy!

### CODE REVIEW

**Comment by MikeMatrix** [comment]
Should we wait until some of this stuff is at least filled with sensible defaults?

**Comment by ackwell** [comment]
Sensible defaults aren't _too_ much of an issue given they're all disabled by default in prod builds - but Nem's taking a look at them now, so we might be able to enable one soon.

**Comment by ackwell** [comment]
Settings have been tweaked to prevent untranslated strings being copied into other locales. In addition, only approved translations get exported into the final data.

It's going to be really important to squash this branch when it gets merged, the system generates a lot of junk.

**Pull request merged**
